app/config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('rooms/', include('rooms.urls', namespace='rooms')),
]

if settings.DEBUG:
    urlpatterns += static(prefix=settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/core/urls.py
from django.urls import path

from rooms import views as rooms_views

app_name = 'core'
urlpatterns = [
    # path('', rooms_views.all_room, name='home'),
    path('', rooms_views.HomeView.as_view(), name='home')
]

app/rooms/urls.py
from django.urls import path

from . import views
app_name = 'rooms'
urlpatterns = [
    path('<int:pk>', views.RoomDetail.as_view(), name='detail'),
    path('search/', views.search, name='search'),
]

app/templates/base.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block page_title %}{% endblock %}| Nbnb</title>
</head>
<body>
<header>
    {% include 'partials/nav.html' %}
    {% block search-bar %}
        <form action="{% url 'rooms:search' %}" method="get">
            <input name="city" placeholder="Search By City">
        </form>
    {% endblock %}
</header>
{% block content %}{% endblock %}

{% include 'partials/footer.html' %}
</body>
</html>